<a href="https://colab.research.google.com/github/rameshuconn/pythonds/blob/main/MatrixAlg_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5]);
a

In [ ]:
a.shape = (5,1);
a

In [ ]:
a = np.array([[1,2,3],[4,5,6]]);
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.random.randint(1,5, size=(3,3));
a

array([[3, 1, 1],
       [4, 2, 3],
       [4, 4, 3]])

In [ ]:
b = np.random.randint(1,5, size=(3,3));
b

array([[3, 4, 2],
       [4, 1, 3],
       [3, 3, 1]])

In [ ]:
np.dot(a,b)

array([[16, 16, 10],
       [29, 27, 17],
       [37, 29, 23]])

In [ ]:
a

array([[3, 1, 1],
       [4, 2, 3],
       [4, 4, 3]])

In [ ]:
a.T

array([[3, 4, 4],
       [1, 2, 4],
       [1, 3, 3]])

In [ ]:
c = a + a.T;
c

array([[6, 5, 5],
       [5, 4, 7],
       [5, 7, 6]])

In [ ]:
c.T

array([[6, 5, 5],
       [5, 4, 7],
       [5, 7, 6]])

In [ ]:
m = np.array([[6,2],[3,1]]);
m

array([[6, 2],
       [3, 1]])

In [ ]:
m.T

array([[6, 3],
       [2, 1]])

In [ ]:
m = np.array([[4,9,2],[5,7,1],[7,7,0]]);
m

array([[4, 9, 2],
       [5, 7, 1],
       [7, 7, 0]])

In [ ]:
m.T

array([[4, 5, 7],
       [9, 7, 7],
       [2, 1, 0]])

In [ ]:
np.transpose(m)

array([[4, 5, 7],
       [9, 7, 7],
       [2, 1, 0]])

In [ ]:
a = np.array([[1,2],[3,4]]);
a

array([[1, 2],
       [3, 4]])

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]]);
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([[3,2],[1,4],[5,6]]);
b

array([[3, 2],
       [1, 4],
       [5, 6]])

In [ ]:
np.dot(a,b)

array([[20, 28],
       [47, 64]])

In [ ]:
a = np.array([[1,4,7],[2,5,8],[3,6,9]]);a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
b = np.array([[1,4],[2,5],[3,6]]);b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.dot(a,b)

array([[30, 66],
       [36, 81],
       [42, 96]])

In [ ]:
c = np.array([[4,1,2],[3,5,1]]);c

array([[4, 1, 2],
       [3, 5, 1]])

In [ ]:
np.dot(
    np.dot(a,b),c
    )

array([[318, 360, 126],
       [387, 441, 153],
       [456, 522, 180]])

In [ ]:
np.dot(
    a,np.dot(b,c)
    )

array([[318, 360, 126],
       [387, 441, 153],
       [456, 522, 180]])

In [ ]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.dot(a,b).T

array([[30, 36, 42],
       [66, 81, 96]])

In [ ]:
np.dot(b.T,a.T)

array([[30, 36, 42],
       [66, 81, 96]])

In [ ]:
5 * (1/5)

1.0

In [ ]:
a = np.random.randint(1,5,size=(3,3));a

array([[2, 3, 2],
       [2, 4, 4],
       [1, 1, 4]])

In [ ]:
a_inv = np.linalg.inv(a)

In [ ]:
a_inv

array([[ 1.5  , -1.25 ,  0.5  ],
       [-0.5  ,  0.75 , -0.5  ],
       [-0.25 ,  0.125,  0.25 ]])

In [ ]:
I = np.dot(a,a_inv);
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.dot(a,I)

array([[2., 3., 2.],
       [2., 4., 4.],
       [1., 1., 4.]])

In [ ]:
a = np.random.randint(1,5,size=(3,3));a

array([[3, 2, 2],
       [1, 4, 1],
       [4, 3, 2]])

In [ ]:
np.diagonal(a)

array([3, 4, 2])

In [ ]:
np.diag(a)

array([3, 4, 2])

In [ ]:
np.diag(np.diag(a))

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 2]])

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
a

array([[3, 2, 2],
       [1, 4, 1],
       [4, 3, 2]])

In [ ]:
b = np.random.randint(1,5,size=(2,2));
b

array([[3, 4],
       [1, 4]])

In [ ]:
np.linalg.det(b)

8.000000000000002

In [ ]:
a

array([[3, 2, 2],
       [1, 4, 1],
       [4, 3, 2]])

In [ ]:
np.linalg.det(a)

-7.000000000000001

In [ ]:
3 * (4*2 - 1*3) - 2 * (1*2-1*4) + 2*(1*3-4*4)

-7

In [ ]:
a

array([[3, 2, 2],
       [1, 4, 1],
       [4, 3, 2]])

In [ ]:
np.linalg.det(a)

-7.000000000000001

In [ ]:
np.linalg.det(a.T)

-6.999999999999998

In [ ]:
b = np.random.randint(1,5,size=(3,3));b
b

array([[3, 2, 1],
       [4, 4, 2],
       [3, 3, 2]])

In [ ]:
np.linalg.det(np.dot(a,b))

-13.999999999999996

In [ ]:
np.dot(np.linalg.det(a),np.linalg.det(b))

-14.000000000000002

In [ ]:
a

array([[3, 2, 2],
       [1, 4, 1],
       [4, 3, 2]])

In [ ]:
np.linalg.matrix_rank(a)

3

In [ ]:
b = np.random.randint(1,5,size=(2,3));b
b

array([[4, 2, 1],
       [3, 1, 3]])

In [ ]:
np.linalg.matrix_rank(b)

2

In [ ]:
c = np.array([[1,2,3],[2,4,6],[3,1,5]]);c

array([[1, 2, 3],
       [2, 4, 6],
       [3, 1, 5]])

In [ ]:
np.linalg.matrix_rank(c)

2

In [ ]:
(-2)*R1 + (1)*R2 = 0;
c1 = -2
c2 = 1

In [ ]:
v = np.random.randint(1,5,size=(20,30));v

array([[2, 2, 3, 1, 3, 1, 2, 3, 2, 3, 2, 2, 4, 2, 1, 3, 2, 3, 2, 1, 4, 3,
        4, 3, 1, 3, 4, 1, 2, 2],
       [2, 1, 1, 4, 4, 4, 4, 1, 1, 4, 4, 3, 3, 4, 3, 4, 2, 3, 2, 2, 1, 1,
        3, 1, 3, 1, 1, 4, 4, 3],
       [3, 3, 4, 3, 3, 1, 3, 4, 4, 3, 4, 1, 2, 3, 1, 2, 3, 2, 1, 2, 1, 2,
        3, 2, 4, 3, 2, 3, 1, 3],
       [2, 1, 3, 2, 4, 1, 3, 1, 1, 4, 1, 4, 3, 1, 2, 4, 2, 1, 3, 4, 2, 1,
        2, 1, 3, 2, 2, 1, 4, 2],
       [4, 2, 4, 3, 1, 2, 3, 1, 4, 3, 1, 2, 1, 3, 2, 2, 3, 3, 1, 1, 2, 2,
        1, 4, 3, 4, 2, 2, 2, 3],
       [1, 1, 3, 3, 1, 1, 4, 4, 3, 4, 1, 4, 1, 4, 4, 3, 1, 1, 3, 1, 4, 2,
        3, 1, 2, 4, 3, 3, 4, 4],
       [3, 4, 4, 3, 1, 2, 1, 4, 4, 1, 4, 2, 1, 1, 3, 1, 4, 3, 1, 4, 1, 4,
        4, 2, 2, 2, 2, 2, 3, 2],
       [2, 4, 3, 3, 2, 3, 4, 3, 4, 2, 1, 4, 4, 1, 4, 4, 2, 2, 1, 4, 2, 2,
        4, 3, 2, 4, 3, 3, 4, 4],
       [2, 4, 4, 3, 1, 1, 3, 1, 4, 4, 1, 1, 1, 2, 1, 3, 4, 3, 3, 3, 3, 2,
        4, 3, 4, 2, 4, 3, 4, 1],
       [2, 2, 2, 3, 3, 3, 4, 2, 1, 1,

In [ ]:
np.linalg.matrix_rank(v)

20

In [ ]:
x = np.random.randint(1,8,size=(2,2));x

array([[5, 3],
       [1, 2]])

In [ ]:
x_inv = np.linalg.inv(x)

In [ ]:
np.dot(x,x_inv)

array([[ 1.00000000e+00, -3.33066907e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [ ]:
np.dot(x,x_inv).astype(int)

array([[1, 0],
       [0, 1]])

In [ ]:
a = np.array([[3,2],[1,5]]);
b = np.array([[2,4],[6,1]]);

In [ ]:
np.linalg.inv(np.dot(a,b))

array([[-0.03146853,  0.04895105],
       [ 0.11188811, -0.06293706]])

In [ ]:
np.dot(np.linalg.inv(b),np.linalg.inv(a))

array([[-0.03146853,  0.04895105],
       [ 0.11188811, -0.06293706]])

In [ ]:
np.linalg.inv(a.T)

array([[ 0.38461538, -0.07692308],
       [-0.15384615,  0.23076923]])

In [ ]:
np.linalg.inv(a).T

array([[ 0.38461538, -0.07692308],
       [-0.15384615,  0.23076923]])

In [ ]:
np.linalg.inv(np.linalg.inv(a))

array([[3., 2.],
       [1., 5.]])

In [ ]:
a

array([[3, 2],
       [1, 5]])